name: Deploy HTML with Cache

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-html
      cancel-in-progress: false

    steps:
    # リポジトリの内容をチェックアウト
    - uses: actions/checkout@v3

    # Dockerキャッシュを有効にする
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Pythonのセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 必要なPythonライブラリをインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4

    # script.pyを実行してmods_data.jsonとindex.htmlを生成
    - name: Run modlist update script
      run: |
        python script.py

    # .nojekyllファイルを作成してJekyllを無効化
    - name: Disable Jekyll
      run: |
        touch .nojekyll

    # 生成されたファイルをGitHubにコミットしてプッシュ
    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add index.html mods_data.json .nojekyll
        git commit -m "Update index.html, mods_data.json and disable Jekyll"
        git push --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # GitHub Pagesにデプロイ
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # ルートディレクトリからデプロイ
