name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # リポジトリの内容をチェックアウト
    - uses: actions/checkout@v3

    # Pythonのセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 必要なPythonライブラリをインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4

    # modlist.htmlファイルとJSONデータの更新を実行
    - name: Run modlist update script
      run: |
        python script.py

    # 未ステージの変更を一時的に保存してリベースする
    - name: Stash any unstaged changes
      run: |
        git stash

    # 最新のリモート変更をフェッチしてリベース
    - name: Pull latest changes
      run: |
        git pull --rebase origin main

    # 保存した未ステージの変更を復元
    - name: Pop stashed changes
      run: |
        git stash pop

    # Gitのユーザー名とメールアドレスを設定
    - name: Set git user
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"

    # 変更をGitHubにコミットしてプッシュ
    - name: Commit and push changes
      run: |
        git add index.html mods_data.json
        git commit -m "Update index.html and mods_data.json"
        git push --force  # 競合があった場合の強制プッシュ
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
