name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-html
      cancel-in-progress: true

    steps:
    # リポジトリの内容をチェックアウト
    - uses: actions/checkout@v3

    # Pythonのセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 必要なPythonライブラリをインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4

    # script.pyを実行してmods_data.jsonとindex.htmlを生成
    - name: Run modlist update script
      run: |
        python script.py

    # 生成されたファイルをGitHubにコミットしてプッシュ
    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add index.html mods_data.json
        git commit -m "Update index.html and mods_data.json"
        git push --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # GitHub Pagesにデプロイ
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # ルートディレクトリからデプロイ
