name: Deploy HTML

# mainブランチにプッシュされたときに実行
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # リポジトリの内容をチェックアウト
    - uses: actions/checkout@v3

    # Pythonのセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 必要なPythonライブラリをインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4

    # modlist.htmlファイルとJSONデータの更新を実行
    - name: Run modlist update script
      run: |
        python script.py

    # 変更をGitHubにコミットしてプッシュ
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html mods_data.json
        git commit -m "Update index.html and mods_data.json"
        git push

    # GitHub Pagesにデプロイ
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # デプロイするディレクトリ（ルートディレクトリ）
